
export const INIT_PODCASTER_DASHBOARD = 'INIT_PODCASTER_DASHBOARD';
export const INIT_PODCASTER_AUDIO_LIST = 'INIT_PODCASTER_AUDIO_LIST';
export const ADD_PODCASTER_AUDIO = 'ADD_PODCASTER_AUDIO';



// player
export const ADD_AUDIO_TO_PLAYLIST_AND_PLAY = 'ADD_AUDIO_TO_PLAYLIST_AND_PLAY';

